version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    # restart: always
  kafka:
    # build: .
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=106.15.93.73
      #- KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.3.1.2:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://106.15.93.73:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CREATE_TOPICS=test:2:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # extra_hosts:
    # - "kafka:10.3.1.2"
    # restart: always
